/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/research': typeof ResearchRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/work': typeof WorkRoute
  '/research/$slug': typeof ResearchSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/research': typeof ResearchRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/work': typeof WorkRoute
  '/research/$slug': typeof ResearchSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/research': typeof ResearchRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/work': typeof WorkRoute
  '/research/$slug': typeof ResearchSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/research'
    | '/roadmap'
    | '/work'
    | '/research/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/research' | '/roadmap' | '/work' | '/research/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/research'
    | '/roadmap'
    | '/work'
    | '/research/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof ResearchRoute
    }
  }
}

interface ResearchRouteChildren {
  ResearchSlugRoute: typeof ResearchSlugRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSlugRoute: ResearchSlugRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ResearchRoute: ResearchRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
